### ISSUE TITLE
creating and automating a run for 300 testcase

### ISSUE THREAD

**Issue by khaledsalem999** [Project-Quantum/Quantum-Starter-Kit#42]
I have a project where I have to automate 300 testcases using this framework, any estimates on how long it will take ?? let us say the average testcase will have 15 steps in it's scenario

thanks in advance

**Comment by ksitwala-perfecto** [comment]
It is difficult to estimate based on the given information because of the following reasons:
- We need to consider how many of these steps will be reusable in after we automate the initial 20-40 scenarios.
- We need to understand the complexity of the flows that you are planning to automate.
- Is it a web application or a mobile application.

Please share the above information.

**Comment by kulin24** [comment]
Closing this case due to inactivity.
